// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import admins "final_project/business/admins"
import context "context"
import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Login provides a mock function with given fields: ctx, email, password
func (_m *Repository) Login(ctx context.Context, email string, password string) (admins.AdminDomain, error) {
	ret := _m.Called(ctx, email, password)

	var r0 admins.AdminDomain
	if rf, ok := ret.Get(0).(func(context.Context, string, string) admins.AdminDomain); ok {
		r0 = rf(ctx, email, password)
	} else {
		r0 = ret.Get(0).(admins.AdminDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Register provides a mock function with given fields: ctx, domain
func (_m *Repository) Register(ctx context.Context, domain admins.AdminDomain) (admins.AdminDomain, error) {
	ret := _m.Called(ctx, domain)

	var r0 admins.AdminDomain
	if rf, ok := ret.Get(0).(func(context.Context, admins.AdminDomain) admins.AdminDomain); ok {
		r0 = rf(ctx, domain)
	} else {
		r0 = ret.Get(0).(admins.AdminDomain)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, admins.AdminDomain) error); ok {
		r1 = rf(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
